### ISSUE TITLE
Markdown link typo

### ISSUE THREAD

**Issue by madsnedergaard** [skovhus/skovhus.github.io#3]
It's kinda weird creating an issue on a personal blog, but just noticed this one 😚 

```diff
- - when should the issue be fixed? We should always be mindful to avoid (context switching)[https://blog.doist.com/context-switching/]
+ - when should the issue be fixed? We should always be mindful to avoid [context switching](https://blog.doist.com/context-switching/)
```

https://github.com/skovhus/skovhus.github.io/blob/3fae402e1eb505325658f1946cad65321a5644b5/src/content/markdown/blog/bug-fixing/index.md#L38

**Comment by skovhus** [comment]
Thanks for flagging this! 🙌

I'll give you write access to the repository. ;)
